### PR TITLE
Update contentscript.js

### PR DESCRIPTION
**Pull request by okiehsch**
You said in https://github.com/uBlockOrigin/uAssets/issues/227 that you wanted to push 2.16 soon,
so I added a few sites to both `Instart Logic` and `Upmanager`, all tested.

### CODE REVIEW

**Comment by gorhill** [comment]
Testing all these represents a lot of work, thanks.

How do you find all these, are you using a crawler?

**Comment by okiehsch** [comment]
For `Instart Logic` yes, from a friend of mine.
For `Upmanager` I use `https://publicwww.com`

**Comment by okiehsch** [comment]
And just for the record I tested these sites over the last week or so, before the Pull request 
I just verified that the sites still used either `Instart Logic` or `Upmanager`

**Comment by okiehsch** [comment]
I also seem to be incappable of sorting a list in alphabetical order, sorry for that.

**Pull request merged**
